#############################################################################
# Makefile for building: TetrisGame
# Generated by qmake (2.01a) (Qt 4.8.1) on: Fri Jul 4 19:37:17 2014
# Project:  TetrisGame.pro
# Template: app
# Command: /usr/bin/qmake -o Makefile TetrisGame.pro
#############################################################################

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = -DQT_WEBKIT -DQT_NO_DEBUG -DQT_GUI_LIB -DQT_CORE_LIB -DQT_SHARED
CFLAGS        = -pipe -O2 -Wall -W -D_REENTRANT $(DEFINES)
CXXFLAGS      = -pipe -O2 -Wall -W -D_REENTRANT $(DEFINES)
INCPATH       = -I/usr/share/qt4/mkspecs/linux-g++ -I. -I/usr/include/qt4/QtCore -I/usr/include/qt4/QtGui -I/usr/include/qt4 -I../../Irrlicht/irrlicht-1.8/include -I. -I.
LINK          = g++
LFLAGS        = -Wl,-O1
LIBS          = $(SUBLIBS)  -L/usr/lib/i386-linux-gnu -L/home/hokan/Irrlicht/irrlicht-1.8/lib/Linux -lIrrlicht -lGL -lX11 -lXxf86vm -lQtGui -lQtCore -lpthread 
AR            = ar cqs
RANLIB        = 
QMAKE         = /usr/bin/qmake
TAR           = tar -cf
COMPRESS      = gzip -9f
COPY          = cp -f
SED           = sed
COPY_FILE     = $(COPY)
COPY_DIR      = $(COPY) -r
STRIP         = strip
INSTALL_FILE  = install -m 644 -p
INSTALL_DIR   = $(COPY_DIR)
INSTALL_PROGRAM = install -m 755 -p
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = sources/main.cpp \
		sources/mainwindow.cpp \
		sources/irrwidget.cpp \
		sources/CGridSceneNode.cpp \
		sources/CFigure.cpp \
		sources/CMoveByStepAnimator.cpp \
		sources/CMoveDownAnimator.cpp \
		sources/CGameFieldManager.cpp \
		sources/CGameManager.cpp \
		sources/CGameFiguresFactory.cpp \
		sources/CGridBox.cpp \
		sources/CUserInputEventReceiver.cpp \
		sources/CGameApplication.cpp \
		sources/Manipulators.cpp moc_mainwindow.cpp \
		moc_irrwidget.cpp
OBJECTS       = main.o \
		mainwindow.o \
		irrwidget.o \
		CGridSceneNode.o \
		CFigure.o \
		CMoveByStepAnimator.o \
		CMoveDownAnimator.o \
		CGameFieldManager.o \
		CGameManager.o \
		CGameFiguresFactory.o \
		CGridBox.o \
		CUserInputEventReceiver.o \
		CGameApplication.o \
		Manipulators.o \
		moc_mainwindow.o \
		moc_irrwidget.o
DIST          = /usr/share/qt4/mkspecs/common/unix.conf \
		/usr/share/qt4/mkspecs/common/linux.conf \
		/usr/share/qt4/mkspecs/common/gcc-base.conf \
		/usr/share/qt4/mkspecs/common/gcc-base-unix.conf \
		/usr/share/qt4/mkspecs/common/g++-base.conf \
		/usr/share/qt4/mkspecs/common/g++-unix.conf \
		/usr/share/qt4/mkspecs/qconfig.pri \
		/usr/share/qt4/mkspecs/modules/qt_webkit_version.pri \
		/usr/share/qt4/mkspecs/features/qt_functions.prf \
		/usr/share/qt4/mkspecs/features/qt_config.prf \
		/usr/share/qt4/mkspecs/features/exclusive_builds.prf \
		/usr/share/qt4/mkspecs/features/default_pre.prf \
		/usr/share/qt4/mkspecs/features/release.prf \
		/usr/share/qt4/mkspecs/features/default_post.prf \
		/usr/share/qt4/mkspecs/features/unix/gdb_dwarf_index.prf \
		/usr/share/qt4/mkspecs/features/warn_on.prf \
		/usr/share/qt4/mkspecs/features/qt.prf \
		/usr/share/qt4/mkspecs/features/unix/thread.prf \
		/usr/share/qt4/mkspecs/features/moc.prf \
		/usr/share/qt4/mkspecs/features/resources.prf \
		/usr/share/qt4/mkspecs/features/uic.prf \
		/usr/share/qt4/mkspecs/features/yacc.prf \
		/usr/share/qt4/mkspecs/features/lex.prf \
		/usr/share/qt4/mkspecs/features/include_source_dir.prf \
		TetrisGame.pro
QMAKE_TARGET  = TetrisGame
DESTDIR       = 
TARGET        = TetrisGame

first: all
####### Implicit rules

.SUFFIXES: .o .c .cpp .cc .cxx .C

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.C.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o "$@" "$<"

####### Build rules

all: Makefile $(TARGET)

$(TARGET): ui_mainwindow.h $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: TetrisGame.pro  /usr/share/qt4/mkspecs/linux-g++/qmake.conf /usr/share/qt4/mkspecs/common/unix.conf \
		/usr/share/qt4/mkspecs/common/linux.conf \
		/usr/share/qt4/mkspecs/common/gcc-base.conf \
		/usr/share/qt4/mkspecs/common/gcc-base-unix.conf \
		/usr/share/qt4/mkspecs/common/g++-base.conf \
		/usr/share/qt4/mkspecs/common/g++-unix.conf \
		/usr/share/qt4/mkspecs/qconfig.pri \
		/usr/share/qt4/mkspecs/modules/qt_webkit_version.pri \
		/usr/share/qt4/mkspecs/features/qt_functions.prf \
		/usr/share/qt4/mkspecs/features/qt_config.prf \
		/usr/share/qt4/mkspecs/features/exclusive_builds.prf \
		/usr/share/qt4/mkspecs/features/default_pre.prf \
		/usr/share/qt4/mkspecs/features/release.prf \
		/usr/share/qt4/mkspecs/features/default_post.prf \
		/usr/share/qt4/mkspecs/features/unix/gdb_dwarf_index.prf \
		/usr/share/qt4/mkspecs/features/warn_on.prf \
		/usr/share/qt4/mkspecs/features/qt.prf \
		/usr/share/qt4/mkspecs/features/unix/thread.prf \
		/usr/share/qt4/mkspecs/features/moc.prf \
		/usr/share/qt4/mkspecs/features/resources.prf \
		/usr/share/qt4/mkspecs/features/uic.prf \
		/usr/share/qt4/mkspecs/features/yacc.prf \
		/usr/share/qt4/mkspecs/features/lex.prf \
		/usr/share/qt4/mkspecs/features/include_source_dir.prf \
		/usr/lib/i386-linux-gnu/libQtGui.prl \
		/usr/lib/i386-linux-gnu/libQtCore.prl
	$(QMAKE) -o Makefile TetrisGame.pro
/usr/share/qt4/mkspecs/common/unix.conf:
/usr/share/qt4/mkspecs/common/linux.conf:
/usr/share/qt4/mkspecs/common/gcc-base.conf:
/usr/share/qt4/mkspecs/common/gcc-base-unix.conf:
/usr/share/qt4/mkspecs/common/g++-base.conf:
/usr/share/qt4/mkspecs/common/g++-unix.conf:
/usr/share/qt4/mkspecs/qconfig.pri:
/usr/share/qt4/mkspecs/modules/qt_webkit_version.pri:
/usr/share/qt4/mkspecs/features/qt_functions.prf:
/usr/share/qt4/mkspecs/features/qt_config.prf:
/usr/share/qt4/mkspecs/features/exclusive_builds.prf:
/usr/share/qt4/mkspecs/features/default_pre.prf:
/usr/share/qt4/mkspecs/features/release.prf:
/usr/share/qt4/mkspecs/features/default_post.prf:
/usr/share/qt4/mkspecs/features/unix/gdb_dwarf_index.prf:
/usr/share/qt4/mkspecs/features/warn_on.prf:
/usr/share/qt4/mkspecs/features/qt.prf:
/usr/share/qt4/mkspecs/features/unix/thread.prf:
/usr/share/qt4/mkspecs/features/moc.prf:
/usr/share/qt4/mkspecs/features/resources.prf:
/usr/share/qt4/mkspecs/features/uic.prf:
/usr/share/qt4/mkspecs/features/yacc.prf:
/usr/share/qt4/mkspecs/features/lex.prf:
/usr/share/qt4/mkspecs/features/include_source_dir.prf:
/usr/lib/i386-linux-gnu/libQtGui.prl:
/usr/lib/i386-linux-gnu/libQtCore.prl:
qmake:  FORCE
	@$(QMAKE) -o Makefile TetrisGame.pro

dist: 
	@$(CHK_DIR_EXISTS) .tmp/TetrisGame1.0.0 || $(MKDIR) .tmp/TetrisGame1.0.0 
	$(COPY_FILE) --parents $(SOURCES) $(DIST) .tmp/TetrisGame1.0.0/ && $(COPY_FILE) --parents headers/mainwindow.h headers/irrwidget.h headers/CGridSceneNode.h headers/CFigure.cpp headers/CMoveByStepAnimator.h headers/CMoveDownAnimator.h headers/CGameFieldManager.h headers/CGameManager.h headers/CGameFiguresFactory.h headers/CGridBox.h headers/CUserInputEventReceiver.h headers/CGameApplication.h headers/Manipulators.cpp .tmp/TetrisGame1.0.0/ && $(COPY_FILE) --parents sources/main.cpp sources/mainwindow.cpp sources/irrwidget.cpp sources/CGridSceneNode.cpp sources/CFigure.cpp sources/CMoveByStepAnimator.cpp sources/CMoveDownAnimator.cpp sources/CGameFieldManager.cpp sources/CGameManager.cpp sources/CGameFiguresFactory.cpp sources/CGridBox.cpp sources/CUserInputEventReceiver.cpp sources/CGameApplication.cpp sources/Manipulators.cpp .tmp/TetrisGame1.0.0/ && $(COPY_FILE) --parents forms/mainwindow.ui .tmp/TetrisGame1.0.0/ && (cd `dirname .tmp/TetrisGame1.0.0` && $(TAR) TetrisGame1.0.0.tar TetrisGame1.0.0 && $(COMPRESS) TetrisGame1.0.0.tar) && $(MOVE) `dirname .tmp/TetrisGame1.0.0`/TetrisGame1.0.0.tar.gz . && $(DEL_FILE) -r .tmp/TetrisGame1.0.0


clean:compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


####### Sub-libraries

distclean: clean
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) Makefile


check: first

mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

compiler_moc_header_make_all: moc_mainwindow.cpp moc_irrwidget.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_mainwindow.cpp moc_irrwidget.cpp
moc_mainwindow.cpp: headers/irrwidget.h \
		headers/CGameApplication.h \
		headers/CGameManager.h \
		headers/CGameFieldManager.h \
		headers/CGameFiguresFactory.h \
		headers/CFigure.h \
		headers/CUserInputEventReceiver.h \
		headers/mainwindow.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) headers/mainwindow.h -o moc_mainwindow.cpp

moc_irrwidget.cpp: headers/CGameApplication.h \
		headers/CGameManager.h \
		headers/CGameFieldManager.h \
		headers/CGameFiguresFactory.h \
		headers/CFigure.h \
		headers/CUserInputEventReceiver.h \
		headers/irrwidget.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) headers/irrwidget.h -o moc_irrwidget.cpp

compiler_rcc_make_all:
compiler_rcc_clean:
compiler_image_collection_make_all: qmake_image_collection.cpp
compiler_image_collection_clean:
	-$(DEL_FILE) qmake_image_collection.cpp
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all: ui_mainwindow.h
compiler_uic_clean:
	-$(DEL_FILE) ui_mainwindow.h
ui_mainwindow.h: forms/mainwindow.ui
	/usr/bin/uic-qt4 forms/mainwindow.ui -o ui_mainwindow.h

compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_moc_header_clean compiler_uic_clean 

####### Compile

main.o: sources/main.cpp headers/mainwindow.h \
		headers/irrwidget.h \
		headers/CGameApplication.h \
		headers/CGameManager.h \
		headers/CGameFieldManager.h \
		headers/CGameFiguresFactory.h \
		headers/CFigure.h \
		headers/CUserInputEventReceiver.h \
		headers/CGridSceneNode.h \
		headers/CMoveByStepAnimator.h \
		headers/CMoveDownAnimator.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o sources/main.cpp

mainwindow.o: sources/mainwindow.cpp headers/mainwindow.h \
		headers/irrwidget.h \
		headers/CGameApplication.h \
		headers/CGameManager.h \
		headers/CGameFieldManager.h \
		headers/CGameFiguresFactory.h \
		headers/CFigure.h \
		headers/CUserInputEventReceiver.h \
		ui_mainwindow.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o mainwindow.o sources/mainwindow.cpp

irrwidget.o: sources/irrwidget.cpp headers/irrwidget.h \
		headers/CGameApplication.h \
		headers/CGameManager.h \
		headers/CGameFieldManager.h \
		headers/CGameFiguresFactory.h \
		headers/CFigure.h \
		headers/CUserInputEventReceiver.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o irrwidget.o sources/irrwidget.cpp

CGridSceneNode.o: sources/CGridSceneNode.cpp headers/CGridSceneNode.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o CGridSceneNode.o sources/CGridSceneNode.cpp

CFigure.o: sources/CFigure.cpp headers/CFigure.h \
		headers/CGameFieldManager.h \
		headers/Manipulators.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o CFigure.o sources/CFigure.cpp

CMoveByStepAnimator.o: sources/CMoveByStepAnimator.cpp headers/CMoveByStepAnimator.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o CMoveByStepAnimator.o sources/CMoveByStepAnimator.cpp

CMoveDownAnimator.o: sources/CMoveDownAnimator.cpp headers/CMoveDownAnimator.h \
		headers/CGameFieldManager.h \
		headers/CFigure.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o CMoveDownAnimator.o sources/CMoveDownAnimator.cpp

CGameFieldManager.o: sources/CGameFieldManager.cpp headers/CGameFieldManager.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o CGameFieldManager.o sources/CGameFieldManager.cpp

CGameManager.o: sources/CGameManager.cpp headers/CGameManager.h \
		headers/CGameFieldManager.h \
		headers/CGameFiguresFactory.h \
		headers/CFigure.h \
		headers/CUserInputEventReceiver.h \
		headers/CMoveDownAnimator.h \
		headers/CGridBox.h \
		headers/CGridSceneNode.h \
		headers/Manipulators.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o CGameManager.o sources/CGameManager.cpp

CGameFiguresFactory.o: sources/CGameFiguresFactory.cpp headers/CGameFiguresFactory.h \
		headers/CFigure.h \
		headers/CGameFieldManager.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o CGameFiguresFactory.o sources/CGameFiguresFactory.cpp

CGridBox.o: sources/CGridBox.cpp headers/CGridBox.h \
		headers/CGridSceneNode.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o CGridBox.o sources/CGridBox.cpp

CUserInputEventReceiver.o: sources/CUserInputEventReceiver.cpp headers/CUserInputEventReceiver.h \
		headers/CGameFieldManager.h \
		headers/CFigure.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o CUserInputEventReceiver.o sources/CUserInputEventReceiver.cpp

CGameApplication.o: sources/CGameApplication.cpp headers/CGameApplication.h \
		headers/CGameManager.h \
		headers/CGameFieldManager.h \
		headers/CGameFiguresFactory.h \
		headers/CFigure.h \
		headers/CUserInputEventReceiver.h \
		headers/CMoveDownAnimator.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o CGameApplication.o sources/CGameApplication.cpp

Manipulators.o: sources/Manipulators.cpp headers/Manipulators.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o Manipulators.o sources/Manipulators.cpp

moc_mainwindow.o: moc_mainwindow.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_mainwindow.o moc_mainwindow.cpp

moc_irrwidget.o: moc_irrwidget.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_irrwidget.o moc_irrwidget.cpp

####### Install

install:   FORCE

uninstall:   FORCE

FORCE:

